/*
*  Author   : Saksham Jain
*  Date     : 04-07-2022
----------------------------------------------------------------------
Version  Date         Author             Remarks
=======   ==========   =============  ==================================
V1.1     04-07-2022  Saksham Jain      to check recursive call
*********************************************/
public class RecursiveTriggerHandler2 {
	public static Boolean isFirstTime = true;
    public static Boolean isFirstTimeOnAdd = true;
    public static Boolean isFirstTimeOnOpp = true;
        public static Boolean isProcessing = false;

}